### ISSUE TITLE
authentication issues

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz-topics/panel-chat-examples#7]
When serving `authentication.py`

I get

```python
2023-09-30 06:43:57,923 Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f085a341f60>>, <Task finished name='Task-72' coro=<async_execute.<locals>.wrapper() done, defined at /home/jovyan/repos/private/panel-chat-examples/.venv/lib/python3.10/site-packages/panel/io/server.py:175> exception=TypeError("object function can't be used in 'await' expression")>)
Traceback (most recent call last):
  File "/home/jovyan/repos/private/panel-chat-examples/.venv/lib/python3.10/site-packages/tornado/ioloop.py", line 738, in _run_callback
    ret = callback()
  File "/home/jovyan/repos/private/panel-chat-examples/.venv/lib/python3.10/site-packages/tornado/ioloop.py", line 762, in _discard_future_result
    future.result()
  File "/home/jovyan/repos/private/panel-chat-examples/.venv/lib/python3.10/site-packages/panel/io/server.py", line 181, in wrapper
    state._handle_exception(e)
  File "/home/jovyan/repos/private/panel-chat-examples/.venv/lib/python3.10/site-packages/panel/io/state.py", line 436, in _handle_exception
    raise exception
  File "/home/jovyan/repos/private/panel-chat-examples/.venv/lib/python3.10/site-packages/panel/io/server.py", line 179, in wrapper
    return await func(*args, **kw)
  File "/home/jovyan/repos/private/panel-chat-examples/.venv/lib/python3.10/site-packages/param/parameterized.py", line 2062, in _async_ref
    raise e
  File "/home/jovyan/repos/private/panel-chat-examples/.venv/lib/python3.10/site-packages/param/parameterized.py", line 2060, in _async_ref
    self_.update({pname: await awaitable})
TypeError: object function can't be used in 'await' expression
```

Futhermore I would suggest 

- An improved flow where it used the environment variable if its set and otherwise asks the user for an api key.
- The chat textinput is disabled if no valid key is available
- If the user removes the key or changes to an invalid key he/ she is again asked for the key. And the chat textinput is disabled until a valid key is available.

**Comment by MarcSkovMadsen** [comment]
I see the same issue in the `chained_response`.

**Comment by ahuang11** [comment]
I feel like this is a param bug. It works on earlier versions.
```

  File "/Users/ahuang/repos/param/param/parameterized.py", line 2042, in _async_ref
    self_.update({pname: await awaitable})
```

**Comment by ahuang11** [comment]
I previously circumvented having users have async functions by doing this:
```python
        # handle async callbacks using this trick
        self._callback_trigger = Button(visible=False)
        self._callback_trigger.on_click(self._prepare_response)
```

```python
    def respond(self):
        """
        Executes the callback with the latest entry in the chat log.
        """
        self._callback_trigger.param.trigger("clicks")
```

However it no longer seems to work. Would like to know what @philippjfr or @maximlt thinks; specifically should I have two separate entry points for async vs sync?

Currently for sync/async callbacks like:
```python


async def ai_respond(contents: str, user: str, instance: pn.widgets.ChatInterface):
    response = await openai.ChatCompletion.acreate(
        model="gpt-3.5-turbo",
        messages=[{"role": "user", "content": contents}],
        stream=True,
    )
    message = ""
    async for chunk in response:
        message += chunk["choices"][0]["delta"].get("content", "")
        yield message
```

Both use the `callback` kwarg:
```python
chat_interface = pn.widgets.ChatInterface(callback=ai_respond)
```

Should I introduce an `async_callback` for async callbacks?
```
chat_interface = pn.widgets.ChatInterface(async_callback=ai_respond)
```

**Comment by philippjfr** [comment]
No likely a change related to Param 2.0. Will resolve that tomorrow.

**Comment by ahuang11** [comment]
> No likely a change related to Param 2.0.

To clarify, Param is _not_ working as expected, and I should not introduce async/sync pairs?

**Comment by maximlt** [comment]
Indeed it looks like a regression in Param 2.0. Luckily it's not yet released so we can fix it.

I've faced a similar issue but that had a difference fix, I was setting a `Callable` parameter value to a method decorated with `param.depends`. Param 2.0 will by default consider that as a reference, while in my case it was just a method that's called by some other parts of the code. I had to set `allow_ref` to `False` for this `Callable`.

**Comment by maximlt** [comment]
I actually didn't get any error serving `authentication.py` with Param from its *main* branch and Panel from the *chat_components* branch.

**Comment by philippjfr** [comment]
>I've faced a similar issue but that had a difference fix, I was setting a Callable parameter value to a method decorated with param.depends. Param 2.0 will by default consider that as a reference, while in my case it was just a method that's called by some other parts of the code. I had to set allow_ref to False for this Callable.

To be clear, Param itself does not yet enable `allow_refs` by default while Panel does.

**Comment by maximlt** [comment]
Ok thanks for that precision, I missed that!
